# Trash Optimizer Datasets Builder configuration file

# Targeted categories for waste classification
[configuration]
input_root_dir = "~/Data/trash-optimizer/datasets"
input_img_extensions = [".jpg", ".jpeg", ".png"]
output_root_dir = "~/Data/trash-optimizer/datasets_processed"
output_dataset_name = "trash_optimizer_dataset"
output_max_per_category = 1000
output_minimum_images_size_wh = [150, 150]
output_augmentation = true
output_categories = [
  "battery",
  "car_battery",
  "cardboard",
  "food_organics",
  "glass",
  "light_bulb",
  "metal",
  "mirror",
  "miscellaneous_trash",
  "neon",
  "paper",
  "pharmacy",
  "plastic",
  "printer_cartridge",
  "tire",
  "wood"
]

# Dataset source configurations
[[configuration.datasets]]
folder_name = "realwaste"
source = "kaggle"
repository = "joebeachcapital/realwaste"
citation = "https://archive.ics.uci.edu/dataset/908/realwaste"

[configuration.datasets.input_output_categories]
"Cardboard" = "cardboard"
"Food Organics" = "food_organics"
"Glass" = "glass"
"Metal" = "metal"
"Miscellaneous Trash" = "miscellaneous_trash"
"Paper" = "paper"
"Plastic" = "plastic"
"Textile Trash" = "textile_trash"
"Vegetation" = "vegetation"

[[configuration.datasets]]
folder_name = "rhwc"
source = "kaggle"
repository = "alistairking/recyclable-and-household-waste-classification"
citation = "https://www.kaggle.com/datasets/alistairking/recyclable-and-household-waste-classification"

[configuration.datasets.input_output_categories]
"aerosol_cans" = "metal"
"aluminum_food_cans" = "metal"
"aluminum_soda_cans" = "metal"
"cardboard_boxes" = "cardboard"
"cardboard_packaging" = "cardboard"
"clothing" = "textile_trash"
"coffee_grounds" = "food_organics"
"disposable_plastic_cutlery" = "plastic"
"eggshells" = "food_organics"
"food_waste" = "food_organics"
"glass_beverage_bottles" = "glass"
"glass_cosmetic_containers" = "glass"
"glass_food_jars" = "glass"
"magazines" = "paper"
"newspaper" = "paper"
"office_paper" = "paper"
"paper_cups" = "paper"
"plastic_cup_lids" = "plastic"
"plastic_detergent_bottles" = "plastic"
"plastic_food_containers" = "plastic"
"plastic_shopping_bags" = "plastic"
"plastic_soda_bottles" = "plastic"
"plastic_straws" = "plastic"
"plastic_trash_bags" = "plastic"
"plastic_water_bottles" = "plastic"
"shoes" = "textile_trash"
"steel_food_cans" = "metal"
"styrofoam_cups" = "miscellaneous_trash"
"styrofoam_food_containers" = "miscellaneous_trash"
"tea_bags" = "food_organics"


[[configuration.datasets]]
folder_name = "customdataset"
source = "custom"
repository = "none"
citation = "none"

[configuration.datasets.input_output_categories]
"battery" = "battery"
"car_battery" = "car_battery"
"light_bulb" = "light_bulb"
"mirror" = "mirror"
"neon" = "neon"
"pharmacy" = "pharmacy"
"printer_cartridge" = "printer_cartridge"
"tire" = "tire"
"wood" = "wood"
